name: Build and Test

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Restore packages (App)
        run: |
          cd simple_live_app
          flutter pub get

      - name: Build APK (App)
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi

      - name: Upload APK (App)
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-*-release.apk

      - name: Restore packages (TV App)
        run: |
          cd simple_live_tv_app
          flutter pub get

      - name: Build APK (TV App)
        run: |
          cd simple_live_tv_app
          flutter build apk --release --split-per-abi

      - name: Upload APK (TV App)
        uses: actions/upload-artifact@v4
        with:
          name: android-tv-app
          path: |
            simple_live_tv_app/build/app/outputs/flutter-apk/app-*-release.apk

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build Windows
        run: |
          cd simple_live_app
          flutter_distributor package --platform windows --targets zip --skip-clean

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: simple_live_app/build/dist/*/*.zip

  build-linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libasound2-dev libmpv-dev mpv

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build Linux
        run: |
          cd simple_live_app
          flutter_distributor package --platform linux --targets zip --skip-clean

      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: simple_live_app/build/dist/*/*.zip
